spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true   # gateway可以发现nacos中的微服务，并自动生成转发路由
      routes:
        - id: service-acl         #设置路由id
          uri: lb://service-acl  #设置路由的uri   lb://nacos注册服务名称 lb表示以负载均衡
          predicates:
            - Path=/admin/**     #表示路径中带 acl 的都去找 service-acl
        - id: service-edu
          uri: lb://service-edu
          predicates:
            - Path=/eduservice/**
        - id: service-msm
          uri: lb://service-msm
          predicates:
            - Path=/edumsm/**
        - id: service-ucenter
          uri: lb://service-ucenter
          predicates:
            - Path=/educenter/**,/api/**
        - id: service-cms
          uri: lb://service-cms
          predicates:
            - Path=/educms/**,/cmsservice/**
        - id: service-order
          uri: lb://service-order
          predicates:
            - Path=/eduorder/**
        - id: service-oss
          uri: lb://service-oss
          predicates:
            - Path=/eduoss/**
        - id: service-statistics
          uri: lb://service-statistics
          predicates:
            - Path=/staservice/**
        - id: service-vod
          uri: lb://service-vod
          predicates:
            - Path=/eduvod/**
