# 最大上传单个文件大小：默认1M
spring:
  servlet:
    multipart:
      #最大上传单个文件大小 默认1M
      max-file-size: 1024MB
      # 最大置总上传的数据大小 ：默认10M
      max-request-size: 1024MB

#阿里云 vod
#不同的服务器，地址不同
aliyun:
  vod:
    file:
      keyid:
      keysecret:
      keyurl: 
