
spring:
  cloud:
     gcp:
      storage:
        credentials:
          location: file:src/main/resources/spring24cmpt474groupproject1-3f7d24db0217.json
      project-id: spring24cmpt474groupproject1